services:
  codeql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/workspace/src  # Put your the directory containing your source code here
      - ./codeql_db:/workspace/db
      - ./scripts:/workspace/scripts
      - ./queries:/workspace/queries
      - ./outputs:/workspace/outputs
    working_dir: /workspace
    # command: ["sleep", "infinity"]
    command: ["python3", "/workspace/scripts/run_ql.py"]
